### ISSUE TITLE
demo only allows rectangles

### ISSUE THREAD

**Issue by z1haze** [djaodjin/djaodjin-annotate#48]
I am considering using this in a project I'm working on, but it appears the demo only lets you use rectangles, no matter which item you click on, text, draw, etc.. its always just a rectangle.. Is this intended?

**Comment by smirolo** [comment]
Thanks for the report.

As it turns out the code depends on bootstrap.js. The test.html page in this repo worked but the [blog post](https://djaodjin.com/blog/jquery-plugin-to-annotate-images.blog.html) was stuck with the rectangle tool because some unrelated work on web page load time optimization had moved loading bootstrap.js after the script element initializing the djaodjin-annotate widget.

If someone is willing to remove the dependency on bootstrap.js (#49), I will merge the pull request. Thanks.
